name: CI

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache - GHA
        uses: actions/cache@v3.0.5
        with:
          path: ~/.cache/coursier/v1/https
          key: ${{ runner.OS }}-coursier-cache

      - name: Add extra resolvers
        run: curl https://${{ secrets.ARTIFACTS_CACHE_BUCKET }}/resolvers.sbt --create-dirs -o ~/.sbt/resolvers.sbt

      - name: Setup
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          java-package: jdk
          architecture: x64

      - name: Clean and test
        run: sbt clean test

      # - name: AWS - Configure
      #   uses: aws-actions/configure-aws-credentials@v1
      #   if: github.actor != 'dependabot[bot]'
      #   with:
      #     aws-access-key-id: ${{ secrets.ARTIFACTS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.ARTIFACTS_SECRET_ACCESS_KEY }}
      #     aws-region: eu-west-1        

      # - name: Cache - Upload
      #   if: github.actor != 'dependabot[bot]'
      #   run: aws s3 sync ~/.cache/coursier/v1/https/ s3://${{ secrets.ARTIFACTS_CACHE_BUCKET }} --sse AES256 --follow-symlinks --no-progress
